### ISSUE TITLE
NoSuchMethodError crash in CodeChickenCore-1.9.4-2.0.4.71-universal

### ISSUE THREAD

**Issue by trevorjd** [TheCBProject/CodeChickenCore#1]
I hope this is the right place. I've been playing this world for a week or so now without a problem. Added EnderStorage today (and CCC) and got this crash a few hours later. Identical crash when trying to reload the world.

http://pastebin.com/nUSeURD9

EnderStorage-1.9.4-2.0.3.62-universal
CodeChickenCore-1.9.4-2.0.4.71-universal
forge 1.10-12.18.0.2000-1.10.0

I tried updating my pack to forge 12.18.1.2011 and 2026 but couldn't make them start.

**Comment by trevorjd** [comment]
I reinstalled the pack and restored my save and manually added mods. Now on forge 12.18.1.2016 and the problem remains.

**Comment by covers1624** [comment]
1.10 is not officoially supported use a dev build of ccl to fix the issue for now

**Comment by trevorjd** [comment]
That's great. Running CCL 2.1.2.45 now and I'm in. Thank you.
