### ISSUE TITLE
Crash when clicking on items in inventory

### ISSUE THREAD

**Issue by Darkosto** [TheCBProject/CodeChickenCore#10]
http://pastebin.com/uAFV8iM6

CCC: 2.4.0.100
MC: 1.10.2
Forge: 2185

Don't know if it's related, but when left clicking on an item to remove from an Alloy smelter it pulls up the recipe page instead.

**Comment by Darkosto** [comment]
Another one: http://pastebin.com/eMJK1b9P

JEI Item Panel was selected with NEI searchbox.

This now happens by only clicking on Nether Quartz in my inventory.

**Comment by covers1624** [comment]
Fixed in NEI 181
