### ISSUE TITLE
Weird Crash from latest version of CodeChickenCore 1.8+

### ISSUE THREAD

**Issue by mcjonesmike** [TheCBProject/CodeChickenCore#12]
I was updating a custom modpack that I play on, and went to update CodeChickenCore & CodeChickenLib. I get this Weird crash whenever the game gets to the initialization phase for the mods. http://pastebin.com/Qj3zbRWt
I have no idea what is causing this, and was wondering if someone could enlighten me.

**Comment by covers1624** [comment]
Update brandons core.
