### ISSUE TITLE
Creeper griefing config not working

### ISSUE THREAD

**Issue by Timeslice42** [TheCBProject/CodeChickenCore#13]
Version 2.4.0.100 in MC 1.10.2
Setting EnvironmentallyFriendlyCreepers to true does not work.

**Comment by Timeslice42** [comment]
Wait... if CCTweaks has this, then go ahead and close the issue.

**Comment by covers1624** [comment]
So, its being moved to CCT, but CCT is not ready yet. There is a game rule for mod griefing, so its not on my priority list.

**Comment by Timeslice42** [comment]
Mob griefing completely neuters creepers. Currently there is no solution for 1.10.2 for preventing creepers from destroying blocks while still allowing them to kill players.

**Comment by covers1624** [comment]
Ah i see, ill get to it soon.

**Comment by Timeslice42** [comment]
Much appreciated :) This tweak is a huge boon to skyblock maps...
Will this be remaining in CCC for the time being?

**Comment by covers1624** [comment]
At the moment all tweaks have been pulled from CCC to a todo folder in CCT. I will how ever get a 1.10 release of cct before i move to 1.11.

**Comment by covers1624** [comment]
This is not needed, tested in 1.7 and 1.10 creepers still damage players with mobGriefing set to false.
