### ISSUE TITLE
Deploader IPFS support / Why is it being deprecated?

### ISSUE THREAD

**Issue by Baughn** [TheCBProject/CodeChickenCore#16]
In practice, people notice deploader mostly when it fails. The main reason it fails is if the backing server goes away; it's otherwise pretty useful.

One way to deal with the problem would be by using IPFS instead, with the HTTPS origin as a backing server only for the unlikely case of the mod falling out of IPFS. To make that less likely to happen, running instances of CCC can act as IPFS servers for the files they've downloaded.

However, you've spent a lot of effort on telling people not to use deploader. This makes me doubt that a PR implementing this would be accepted.

Would you care to give me a bit of guidance as to why? Is there an alternative planned (or already-existing) which I don't know about, or are there deeper problems which would need to be fixed before it'd make sense?

(Left to my own devices, I'm likely to go write my own mod-downloader mod.)

**Comment by covers1624** [comment]
The DepLoader was a really hacky solution to a simple problem, how do i get my non mod jar (CCL) to be installed along side CCC, the solution in this case was the DepLoader, as things are moving in a different direction the dep loader is no longer needed and frankly should never have come in to existence, Mods downloading mods is a huge security risk and i will not be taking part in any such action. CCL is now a full on mod so it has a container and all.
