### ISSUE TITLE
Builds?

### ISSUE THREAD

**Issue by NoOneNo** [TheCBProject/CodeChickenCore#2]
Where are the builds for this?

**Comment by covers1624** [comment]
The maven is at: http://adel.podgeweb.com:1616/maven/

**Comment by NoOneNo** [comment]
Thank you.

**Comment by bookerthegeek** [comment]
Most likely would be good to put into the readme.

**Comment by covers1624** [comment]
Sure, it will be changing in the next few weeks to a dedicated server, just need to purchase the domain. Currently on a friends domain.
