### ISSUE TITLE
Incompatibility with SpongeForge?

### ISSUE THREAD

**Issue by Nullga** [TheCBProject/CodeChickenCore#2]
Tho I'm on 1.10.2. I appreciate if you could look into this. 

As an error message, "Oh dear. Sponge could not apply one or more patches. A required class was loaded prematurely! ".

http://pastebin.com/C4iQneTt

Thanks.

**Comment by covers1624** [comment]
I don't support 1.10 yet, also I don't support any sort of sponge/bukkit/thermos environment, you will have to get them to debug this.

**Comment by covers1624** [comment]
Should be fixed in latest build.
