### ISSUE TITLE
Help with writing ASMModularTransformer

### ISSUE THREAD

**Issue by miuirussia** [TheCBProject/CodeChickenCore#21]
I backporting my fix (https://github.com/MinecraftForge/MinecraftForge/commit/b6194b0cca925d5560616f2f8f6246cf4421d6cf) from 1.11.2 to 1.10.2. I decided to use CCL for simple transforming method, but it crashes after loading with exception: 
[crash-2017-04-04_23.32.10-client.txt](https://github.com/TheCBProject/CodeChickenCore/files/894291/crash-2017-04-04_23.32.10-client.txt)
ccl_modular output:
[bgu.txt](https://github.com/TheCBProject/CodeChickenCore/files/894294/bgu.txt)

My mod source here:
https://github.com/miuirussia/BaseMod

Can someone provide some help with this? Thanks advance!

**Comment by covers1624** [comment]
So few things, You probably need to read up on how bytecode works. There is also a few things to keep in mind with CCL's system, Instructions in your ASM file must be in SRG names (func_blah / field_blah). You are also running your transformer too late, nuke your @SortingIndex annotation in your LoadingPlugin, CCL's asm pipe runs of OBF names.

**Comment by covers1624** [comment]
Also, you don't need a mod container if you don't want one.

**Comment by miuirussia** [comment]
Thanks for the quick response! I'll try to fix it tomorrow. For bytecode I use ASMifier (http://asm.ow2.org/asm40/javadoc/user/org/objectweb/asm/util/ASMifier.html) and than diffed two output ASM files for creating this patch, I hope that the code in patch is correct.

**Comment by covers1624** [comment]
Should be from what i saw, Make sure you change all MC references to SRG names, you are referencing a fields deobf name.

**Comment by miuirussia** [comment]
Yes, I fixed it and it works. Thanks for helping!

**Comment by covers1624** [comment]
So your issue has been resolved?

**Comment by miuirussia** [comment]
Yes
