### ISSUE TITLE
Finite water startup crash

### ISSUE THREAD

**Issue by megaloloful** [TheCBProject/CodeChickenCore#3]
When you enable the finite water config the game crashes instantly when you try to launch it without creating a crashlog.

Tested in an instance with forge 12.16.0.1865 CodeChickenCore 1.9-2.0.1.50 and ChickenLib 1.9-2.0.1.21

**Comment by covers1624** [comment]
Can you post your latest.log file please?

**Comment by covers1624** [comment]
Should be fixed with latest build on curse.
