### ISSUE TITLE
dep loader downloading wrong version of codechickenLib

### ISSUE THREAD

**Issue by SDUBZ** [TheCBProject/CodeChickenCore#6]
its meant to download CodeChickenLib-1.10.2-2.4.2.106-universal instead it downloads CodeChickenLib-1.10.2-2.4.1.97-universal and deletes CodeChickenLib-1.10.2-2.4.2.106-universal and replaces it with  CodeChickenLib-1.10.2-2.4.1.97-universal

please help

**Comment by covers1624** [comment]
CCL should not be downloaded by the deploader, it should delete any ccl version in /mods/mcversion
Place the new CCL in your mods folder and the old one should be removed.

**Comment by C0rn3j** [comment]
>CCL should not be downloaded by the deploader

Except CCL is getting pulled on MC start, and the wrong version on top of that.

How about adding a curseforge page for CCL and disable the automatic downloading if you don't like the behavior?

**Comment by covers1624** [comment]
That is what I have done.. like I said on the latest ccc, ccl will not be auto downloaded, and a normal mod dep is applied. Can you please give me a full mod list/modpack you are using

**Comment by SDUBZ** [comment]
all mods are listed here https://minecraft.curseforge.com/projects/sdubzskycraft and i downloaded codechickenLib manually and added it and it still deleted it and also through curse launcher and still same behaviour

**Comment by covers1624** [comment]
Ahhh, its BrandonsCore doing it. Ive already pushed update to BrandonsCore to use a new version of the Deploader, just @brandon3055 forgot to push a build.

**Comment by SDUBZ** [comment]
oh good to hear thanks , i was wondering what was causing this

**Comment by covers1624** [comment]
Brandon has pushed a BrandonsCore update, can you please verify this issue again.

**Comment by SDUBZ** [comment]
well the brandon core wants download 2.4.1 but codechickenlib is staying put now for me, not sure if its gonna work good with curses modpack releases, i will release a update soon and get back to you if it all downloads and works as intended

**Comment by SDUBZ** [comment]
seems to work beautifully now even with curse thanks man for tracking down the cause :D

**Comment by covers1624** [comment]
No problem.

**Comment by SDUBZ** [comment]
i thought id let you know mekanism is still using deploader ive posted on his github and twitter and gotten no where regarding it
