### ISSUE TITLE
TextureFX crash

### ISSUE THREAD

**Issue by nikita488** [TheCBProject/CodeChickenCore#6]
When i turn in config "replaceLavaFX" to true i get this crash:
http://pastebin.com/JXCMk5cJ

**Comment by covers1624** [comment]
What did this do in 1.7, honestly iv'e never used it.

**Comment by nikita488** [comment]
It's return texture animation system from 1.4.7 (and older) and in CodeChickenCore it's used for return old water/lava textures from 1.4.7. And i think @Soaryn use this in his XyCraft too.

**Comment by covers1624** [comment]
Ok, ill look in to it more deeply now, I have some changes coming that will require a version bump for CCC so its a good time to do it.
