### ISSUE TITLE
[1.10.2] Finite Water config gone?

### ISSUE THREAD

**Issue by Kiyaku** [TheCBProject/CodeChickenCore#7]
Heya,

i was using the finite water options from codechickencore but it seems to not be available anymore with the latest version. 

Is this gonna be gone for good or will this be added again in the future? Should i just switch to an older version again? 

Thanks,
SC

**Comment by covers1624** [comment]
I am in the process of porting all the tweak stuff out of ccc to a new mod, CCTweaks is it's name, keep an eye on the repo for content, that probably means I've pushed it to curse.

**Comment by Kiyaku** [comment]
Good to know, thanks!
