### ISSUE TITLE
Code chicken core and lib

### ISSUE THREAD

**Issue by Medusalem** [TheCBProject/CodeChickenCore#8]
Hey, I am updating my Modpack and i think i found kind of a Bug....

If i install the newest version of CodechickenCore and Lib, removing the old version out the MCVERSION folder, Forge is removin the new version and putting the old code chicken lib back in, code chicken core stopping minecraft, because it is missing the right lib.

So Forge is removing Codechickenlib if it is in the minecraft Mods folder.

Core Version: 1,10,2-2,3,4,89-universal
code chicken version i try to instal: 1,10,2-2,4,2,106-universal
Forge version:  12,18,2,2111

Here would be the log minecraft is heanding me over: http://pastebin.com/6uSGmi6S
(if i do it normaly, like i should!) After that the codechickenlib is back in mcversion folder with version 2.2.3.73

If i can give you any more information just ask :)

**Comment by covers1624** [comment]
Update BrandonsCore.

**Comment by Morpheus1101** [comment]
You no longer need the 1.10.2 folder as the mods are all normal mods now an go in the main mods/ directory rather than mods/1.10.2/ directory

**Comment by covers1624** [comment]
This was an outdated BC issue.
