### ISSUE TITLE
1.11 doesn't run in a dev environment

### ISSUE THREAD

**Issue by DaMatrix** [TheCBProject/CodeChickenCore#9]
... yeah.

**Comment by covers1624** [comment]
probably a thing, it was a real quick port about 2 hours after the forge branch was public.. Ill end up scraping what i have for 1.11 as i have added features to master since that port. I expect to be doing 1.11 soon ish, hopefully in the next week or so.

**Comment by DaMatrix** [comment]
ok, great :D
